### ISSUE TITLE
Duplicated comment in Shop.yml

### ISSUE THREAD

**Issue by Chris6ix** [7sat/DShop3#60] opened 2022-02-10 19:30 UTC
The comment `# Shop name can not contain formatting codes, '/' and ' '` is duplicated in the Shop.yml file

**Comment by 7sat** [comment] 2022-02-16 17:08
It seems to be fixed now.

**Comment by 7sat** [comment] 2022-02-17 15:20
The problem may be that the template uploaded to Pastebin contains comments. not sure. At least on my server it doesn't reproduce anymore.

**Closed** 2022-02-18 16:19 UTC
Labels: bug
